apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-1h
spec:
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1800
      backoffLimit: 0
      template:
        spec:
          volumes:
          - name: usercert
            secret:
              secretName: "{{ .Values.cronjobSettings.usercert }}"
          - name: userkey
            secret:
              secretName: "{{ .Values.cronjobSettings.userkey }}"
          {{- range $key, $val := .Values.persistentVolumes }}
          - name: {{ $key }}
            persistentVolumeClaim:
              claimName: {{ $val.name }}
          {{- end}}
          containers:
            - name: {{ .Release.Name }}-1h
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              volumeMounts:
                - name: usercert
                  mountPath: /opt/rucio/certs/
                - name: userkey
                  mountPath: /opt/rucio/keys/
                {{- range $key, $val := .Values.persistentVolumes }}
                - name: {{ $key }}
                  mountPath: {{ $val.mountPath }}
                {{- end}}
              env:
                - name: RUCIO_HOME
                  value: "/opt/rucio-{{ .Values.cronjobSettings.instance }}"
                - name: TEST_SUFFIX
                  value: "{{ .Values.cronjobSettings.instance }}"
                - name: GITLAB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: "rucio-secrets"
                      key: gitlab_token
                - name: MONIT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: "rucio-secrets"
                      key: monit_token
{{- with .Values.cronjobSettings.additionalEnvs }}
{{ toYaml . | indent 16 }}
{{- end }}
              command: ['/root/CMSRucio/docker/rucio_client/scripts/k8s_sync_sites.sh']
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-12h
spec:
  schedule: "10 */12 * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 7200
      backoffLimit: 0
      template:
        spec:
          volumes:
          - name: usercert
            secret:
              secretName: "{{ .Values.cronjobSettings.usercert }}"
          - name: userkey
            secret:
              secretName: "{{ .Values.cronjobSettings.userkey }}"
          {{- range $key, $val := .Values.persistentVolumes }}
          - name: {{ $key }}
            persistentVolumeClaim:
              claimName: {{ $val.name }}
          {{- end}}
          containers:
            - name: {{ .Release.Name }}-12h
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              volumeMounts:
                - name: usercert
                  mountPath: /opt/rucio/certs/
                - name: userkey
                  mountPath: /opt/rucio/keys/
                {{- range $key, $val := .Values.persistentVolumes }}
                - name: {{ $key }}
                  mountPath: {{ $val.mountPath }}
                {{- end}}
              env:
                - name: RUCIO_HOME
                  value: "/opt/rucio-{{ .Values.cronjobSettings.instance }}"
                - name: TEST_SUFFIX
                  value: "{{ .Values.cronjobSettings.instance }}"
                - name: GITLAB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: "rucio-secrets"
                      key: gitlab_token
                - name: MONIT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: "rucio-secrets"
                      key: monit_token
                - name: IAM_SERVER
                  value: "{{ .Values.oidc.iamServer }}"
                - name: IAM_CLIENT_ID
                  value: "{{ .Values.oidc.iamClientId }}"
                - name: IAM_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: "rucio-secrets"
                      key: oidc_iam_client_secret
                      optional: true
{{- with .Values.cronjobSettings.additionalEnvs }}
{{ toYaml . | indent 16 }}
{{- end }}
              command: ['/root/CMSRucio/docker/rucio_client/scripts/k8s_sync_users_links.sh']
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rucio-subscriptions
  namespace: {{ .Values.dmops_namespace }}
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: dmtops-spark-svc
        spec:
          volumes:
          - name: dmtops-cron-secrets
            secret:
              secretName: dmtops-cron-secrets
          containers:
            - name: rucio-subscriptions
              image: "{{ .Values.dmops_image.repository }}:{{ .Values.dmops_image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.dmops_image.pullPolicy }}
              volumeMounts:
                - name: dmtops-cron-secrets
                  mountPath: /etc/secrets
                  readOnly: true
              env:
                - name: DRIVERPORT
                  value: "31203"
                - name: BMPORT
                  value: "31204"
                - name: K8SHOST
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
              ports:
                - containerPort: 31203 # spark.driver.port
                  name: port-0
                - containerPort: 31204 # spark.driver.blockManager.port
                  name: port-1
              command: ['/src/submit_rucio_subscriptions.sh']
          restartPolicy: OnFailure